name: budget_bayani
description: A finance app made in compliance with the Final Academic Project for ICS26011
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  sqflite: ^2.1.0+1
  pie_chart: ^5.4.0
  progresso: ^0.3.0
  intl: ^0.17.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
